# Site settings
title: Koji Labs
email: matt.west@kojilabs.com
author: Matt West
description: Web Design Studio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kojilabs.com" # the base hostname & protocol for your site
twitter_username: kojilabs
github_username:  kojilabs

# Build settings
markdown: kramdown
kramdown:
  input: GFM

permalink: /blog/:title/

sass:
  style: :compressed
  sass_dir: assets/sass

assets:
  js_compressor: uglifier
  css_compressor: sass

category_dir: blog/category

tag_page_layout: tag_page
tag_page_dir: blog/tag
tag_permalink_style: pretty

authors:
  mattwest:
    name: Matt West
    display_name: Matt West
    gravatar: 61695a5d7512d464d38af376b10824b8
    email: matt.west@kojilabs.com
    web: http://mattwest.io
    twitter: mattantwest
    github: matt-west
    bio: Founder of Koji Labs, tech entrepreneur, and author of HTML5 Foundations.
